CREATE TABLE SALESMAN_MASTER_1
(   SALESMANNO VARCHAR(6) PRIMARY KEY CHECK(SALESMANNO LIKE 'S%'),
	SALESMANNAME VARCHAR(20) NOT NULL,
    ADDRESS1 VARCHAR(30) NOT NULL,
    ADDRESS2 VARCHAR(30),
    CITY VARCHAR(20),
    PINCODE INTEGER,
    STATE VARCHAR(20),
    SALAMT REAL NOT NULL CHECK(SALAMT>0) DEFAULT 1000.0,
    TGTTOGET DECIMAL NOT NULL CHECK(TGTTOGET !=0) DEFAULT 100,
    YTDSALES DOUBLE NOT NULL DEFAULT 100,
    REMARKS VARCHAR(60)
);

INSERT INTO SALESMAN_MASTER_1
    (SALESMANNO ,SALESMANNAME,ADDRESS1 ,ADDRESS2 ,CITY ,PINCODE ,STATE)
VALUES
    ('S00001', 'Aman', 'A/14', 'Worli', 'Mumbai', 400002, 'Maharashtra'),
    ('S00002', 'Omkar', '65', 'Nariman', 'Mumbai', 400001, 'Maharashtra'),
    ('S00003', 'Raj', 'P-7', 'Bandra', 'Mumbai', 400032, 'Maharashtra'),
    ('S00004', 'Ashish', 'A/5', 'Juhu', 'Mumbai', 400044, 'Maharashtra');
SELECT *
FROM SALESMAN_MASTER_1;


CREATE TABLE AUTHOR
(
    AUTHOR_ID VARCHAR(5) PRIMARY KEY,
    LASTNAME VARCHAR(15) NOT NULL,
    FIRSTNAME VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(40),
    CITY VARCHAR(15),
    COUNTRY VARCHAR(15)
);
INSERT INTO AUTHOR
    (AUTHOR_ID, LASTNAME, FIRSTNAME, EMAIL, CITY, COUNTRY)
VALUES('01', 'SETH', 'VIKRAM', 'VIKRAM@GMAIL.COM', 'PUNE', 'INDIA'),
    ('02', 'NARAYAN', 'R', 'NARAYAN@GMAIL.COM', 'GOA', 'INDIA'),
    ('03', 'SINGH', 'KHUSHWANT', 'SINGH@GMAIL.COM', 'DELHI', 'INDIA'),
    ('04', 'ROY', 'ARUN', 'ARUN@GMAIL.COM', 'MUMBAI', 'INDIA');
SELECT *
FROM AUTHOR;


CREATE TABLE BOOK
(
    BOOK_ID VARCHAR(5) PRIMARY KEY CHECK(BOOK_ID LIKE 'B%'),
    BOOK_TITLE VARCHAR(20) NOT NULL,
    COPIES INT CHECK(COPIES>2) DEFAULT 3
);
INSERT INTO BOOK
    (BOOK_ID,BOOK_TITLE,COPIES)
VALUES('B1', 'ALCHEMIST', 4),
    ('B2', 'ART OF WAR', 4),
    ('B3', 'POKE THE BOX', 5),
    ('B4', 'TIME', 6);
SELECT *
FROM BOOK;


CREATE TABLE AUTHOR_LIST
(
    AUTHOR_ID VARCHAR(5) REFERENCES AUTHOR(AUTHOR_ID),
    BOOK_ID VARCHAR(5),
    ROLE VARCHAR(15),
    PRIMARY KEY (AUTHOR_ID,BOOK_ID)
);
INSERT INTO AUTHOR_LIST
    (AUTHOR_ID,BOOK_ID,ROLE)
VALUES
    ('05', 'B5', 'THRILLER'),
    ('06', 'B6', 'COMEDY'),
    ('07', 'B7', 'ACTION'),
    ('08', 'B8', 'SUSPENSE');
SELECT *
FROM AUTHOR_LIST;
ALTER TABLE AUTHOR_LIST ADD PUBLISHER VARCHAR(30);