/*1.    Create the following two tables (EMP and DEPT)*/

CREATE TABLE DEPT
(
		DEPTNO INT PRIMARY KEY,
    	DNAME VARCHAR(20),
    	LOC VARCHAR(20)
);

INSERT INTO DEPT
	(DEPTNO, DNAME, LOC)
VALUES
	(10, 'ACCOUNTING', 'NEW YORK'),
    (20, 'RESEARCH', 'DALLAS'),
    (30, 'SALES', 'CHICAGO'),
    (40, 'OPERATIONS', 'BOSTON');
    
SELECT * 
FROM DEPT;

CREATE TABLE EMP
(
    EMPNO INT PRIMARY KEY,
    ENAME VARCHAR(30),
    JOB VARCHAR(30),
    MGR INT,
    HIREDATE DATE,
    SAL INT,
    COMM INT,
    DEPTNO INT REFERENCES DEPT(DEPTNO)
);


INSERT INTO EMP
    (EMPNO , ENAME , JOB , MGR , HIREDATE , SAL , COMM , DEPTNO)
VALUES
    ( 7369 , 'SMITH' , 'CLERK' , 7902 , '1980-12-17', 500 , 800 , 20);
INSERT INTO EMP
    (EMPNO , ENAME , JOB , MGR , HIREDATE , SAL , COMM , DEPTNO)
VALUES
    ( 7499 , 'ALLEN' , 'SALESMAN' , 7698 , '1981-02-20' , 1600 , 300 , 30);
   
INSERT INTO EMP
    (EMPNO , ENAME , JOB , MGR , HIREDATE , SAL , COMM , DEPTNO)
VALUES
	( 7521 , 'WARD' , 'SALESMAN' , 7698 , '1981-02-22' , 1250 , 500 , 30);
    
INSERT INTO EMP
	(EMPNO , ENAME , JOB , MGR , HIREDATE , SAL, DEPTNO)
VALUES
	(7566,'JONES','MANAGER', 7839,'1981-04-02', 2975, 20);
    
INSERT INTO EMP
    (EMPNO , ENAME , JOB , MGR , HIREDATE , SAL , COMM , DEPTNO)
VALUES
	(7654, 'MARTIN', 'SALESMAN', 7698, '1981-09-28', 1250, 1400, 30);
    
INSERT INTO EMP
	(EMPNO , ENAME , JOB , MGR , HIREDATE , SAL, DEPTNO)
VALUES
	(7698, 'BLAKE', 'MANAGER', 7839, '1981-05-01', 2850, 30);

INSERT INTO EMP
	(EMPNO , ENAME , JOB , MGR , HIREDATE , SAL, DEPTNO)
VALUES
    (7782, 'CLARK', 'MANAGER', 7839, '1981-06-09', 2450, 10);
    
INSERT INTO EMP
	(EMPNO , ENAME , JOB , MGR , HIREDATE , SAL, DEPTNO)
VALUES
    (7788, 'SCOTT', 'ANALYST', 7566, '1982-12-09', 3000, 20);


INSERT INTO EMP
	(EMPNO , ENAME , JOB , HIREDATE , SAL, DEPTNO)
VALUES
	( 7839, 'KING', 'PRESIDENT', '1981-11-17', 5000, 10);
    
INSERT INTO EMP
    (EMPNO , ENAME , JOB , MGR , HIREDATE , SAL , COMM , DEPTNO)
VALUES
	(7844, 'TURNER', 'SALESMAN', 7698, '1981-09-08', 1500, 0, 30);



INSERT INTO EMP
	(EMPNO , ENAME , JOB , MGR , HIREDATE , SAL, DEPTNO)
VALUES
	(7876, 'ADAMS', 'CLERK', 7788, '1983-01-12', 1100, 20);

INSERT INTO EMP
	(EMPNO , ENAME , JOB , MGR , HIREDATE , SAL, DEPTNO)
VALUES
    ( 7900, 'JAMES', 'CLERK', 7698,'1981-12-03', 950, 30);

INSERT INTO EMP
	(EMPNO , ENAME , JOB , MGR , HIREDATE , SAL, DEPTNO)
VALUES
    ( 7902, 'FORD', 'ANALYST', 7566,'1981-12-03', 3000, 20);
INSERT INTO EMP
	(EMPNO , ENAME , JOB , MGR , HIREDATE , SAL, DEPTNO)
VALUES
    (7934, 'MILLER', 'CLERK', 7782, '1982-01-23', 1300, 10);
    

SELECT * 
FROM EMP;

/*Write the Nested Queries for the following queries.*/

/*1. List the details of the emps whose Salaries more than the employee BLAKE*/
SELECT *
FROM EMP
WHERE SAL>(SELECT SAL FROM EMP WHERE ENAME='BLAKE');

/*2. List the emps whose Jobs are same as ALLEN.*/
SELECT ENAME 
FROM EMP 
WHERE JOB=(SELECT JOB FROM EMP WHERE ENAME='ALLEN');

/*3. List the Emps whose Sal is same as FORD or SMITH in desc order of Names. */
SELECT ENAME 
FROM EMP
WHERE SAL=(SELECT SAL FROM EMP WHERE ENAME='FORD') OR SAL=(SELECT SAL FROM EMP WHERE ENAME='SMITH')
ORDER BY ENAME DESC;

/*4. List the emps Whose Jobs are same as MILLER or Sal is more than ALLEN.*/
SELECT ENAME 
FROM EMP
WHERE JOB=(SELECT JOB FROM EMP WHERE ENAME='MILLER') OR SAL>(SELECT SAL FROM EMP WHERE ENAME='ALLEN');

/*5. Find the highest paid employee of sales department. */
SELECT ENAME 
FROM EMP
WHERE SAL=(SELECT MAX(SAL) FROM EMP WHERE DEPTNO =(SELECT DEPTNO FROM DEPT WHERE DNAME='SALES'));

/*6. List the employees who are senior to most recently hired employee working under king. */
SELECT * 
FROM EMP
WHERE HIREDATE< Any(SELECT HIREDATE FROM EMP WHERE DEPTNO =(SELECT DEPTNO FROM EMP WHERE ENAME='KING')); 

SELECT *
FROM EMP
WHERE HIREDATE <
    (SELECT MAX(HIREDATE)
     FROM EMP
     WHERE EMPNO IN
         (SELECT EMPNO
          FROM EMP
          WHERE ENAME = 'KING'));


/*7. List the names of the emps who are getting the highest sal dept wise.*/
SELECT ENAME 
FROM EMP 
WHERE SAL = (SELECT MAX(SAL) FROM EMP ORDER BY DEPTNO); 

/*8. List the emps whose sal is equal to the average of max and minimum*/
SELECT * FROM EMP
WHERE SAL = (SELECT (MAX(SAL)+MIN(SAL))/2 FROM EMP);

/*9. List the emps who joined in the company on the same date.*/
SELECT * FROM EMP E
WHERE HIREDATE IN (SELECT HIREDATE FROM EMP WHERE E.EMPNO <> EMPNO);

/*10. Find out the emps who joined in the company before their Managers*/
SELECT E.ENAME,E.HIREDATE
FROM EMP E,EMP M
WHERE E.MGR=M.EMPNO
AND E.HIREDATE<M.HIREDATE;
